site_name: Munich Imputation Server

theme: readthedocs

nav:
- Home: index.md
- Getting Started: getting-started.md
- Data Preparation: prepare-your-data.md
- Reference Panels: reference-panels.md
- Pipeline Overview: pipeline.md
- Security: data-sensitivity.md
- FAQ: faq.md
- Developer Documentation:
  - API: api.md
  - Docker: docker.md
  - Create Reference Panels: create-reference-panels.md
- Contact: contact.md

repo_name: itguser/munichimputationserver
repo_url: https://github.com/itguser/munichimputationserver
edit_uri: edit/master/docs

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/itguser/munichimputationserver 

markdown_extensions:
    - toc:
        permalink:
    - admonition:
